site_name: Citizen Clinic Cybersecurity Education Center
site_url: 'https://cltc-berkeley.github.io/resources-beta'
docs_dir: markdown/
site_dir: docs/

repo_name: 'cltc-berkeley/resources-beta'
repo_url: 'https://github.com/cltc-berkeley/resources-beta'
edit_uri: '/cltc-berkeley/resources-beta/tree/master/markdown'

plugins:
    - search
    - git-revision-date-localized
    #- pdf-export:
    #    combined: false

nav:
    - Home: index.md
    - Curriculum:
        - Lesson Modules: 
          - Introduction: Clinic_Curriculum/Lesson_Modules.md
          - Code of Conduct & Ethics: 
            - Ethics Overview: Clinic_Curriculum/Modules/Ethics/Ethics.md
            - Code of Conduct: Clinic_Curriculum/Modules/Ethics/Student_Code_of_Conduct.md
          - Contextual and Capacity Research:
            - Contextual Research Overview: Clinic_Curriculum/Modules/Contextual_Research/Contextual_Research.md
            - PESTLE-M Worksheet: Clinic_Curriculum/Modules/Contextual_Research/PESTLE-M_Worksheet.md
            - Contextual Assessment Requirements: Clinic_Curriculum/Modules/Contextual_Research/Contextual_Assessment_Info_Reqs.md            
          - Harmful Information (Misinformation and Harassment): 
            - Harmful Information Overview: Clinic_Curriculum/Modules/Harmful_Information/Harmful_Information.md
            - Mitigation Framework: Clinic_Curriculum/Modules/Harmful_Information/Mitigation_Framework.md
        - Entire Syllabus: 
          - Spring 2020 (Current): Clinic_Curriculum/Clinic_Syllabus_Spring_2020.md
          - Fall 2019: Clinic_Curriculum/Clinic_Syllabus_Fall_2019.md
          - Spring 2019: Clinic_Curriculum/Clinic_Syllabus_Spring_2019.md
          - Fall 2018: Clinic_Curriculum/Clinic_Syllabus_Fall_2018.md
    - Infrastructure:
        - Virtual Private Network: Clinic_Infrastructure/VPN.md
        - Virtual Identities: Clinic_Infrastructure/Virtual_Identities.md
        - Phishing Simulation: Clinic_Infrastructure/Phishing_Simulation.md
    - Baseline Organizational Security Guide:
        - Introduction: LRO/0-Introduction_and_TOC_(README).md
        - Why do Low-Risk Organizations Need Cybersecurity?: LRO/1-Why_Do_Low-Risk_Organizations_Need_Cybersecurity.md
        - Common Cybersecurity Controls: LRO/2-Common_Cybersecurity_Controls.md
        - Additional Cybersecurity Best Practices: LRO/3-Additional_Cybersecurity_Best_Practices.md
        - Appendix A - Building a Security Policy for Your Organization: LRO/4-Appendix_A_Building_a_Security_Policy.md
        - Appendix B - Implementation Guidance: LRO/5-Appendix_B_Implementation_Guidance.md
        - Appendix C - Moving Beyond the Baseline: LRO/6-Appendix_C_Moving_Beyond_the_Baseline.md


theme:
  name: material
  custom_dir: clinic_theme
  logo: 'images/logo.png'
  favicon: 'assets/images/favicon.png'
  feature:
    tabs: true
  palette:
    primary: 'white'
    accent: 'indigo'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  next_previous: true

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.magiclink
